---

- name: Vagrant Setup
  hosts: default

  tasks:
    - name: Install some stuff
      become: yes
      apt:
        name: "{{ item }}"
      with_items:
        - git
        - vim

    - name: Clone repositories
      git:
        dest: /srv/backend/backend-1
        repo: https://github.com/cofee-on-me/backend-1.git
